---
title: "HOMEWORK1"
output: html_notebook
---
## **Ceyhun Onur**

## _18/10/2019_

# Task 1
Needed packages:
```{r include=FALSE}
installed.packages("data.table")
library(data.table)
```
## Subtask 1
```{r}
# Read frome the snapshot, select only columns we're interested in.
matches <- fread("/home/ceyonur/git/CMPE/fall19-ceyonur/data/homework1/matches.csv", select=c("match_id", "league_id","match_status","match_hometeam_score", "match_awayteam_score"))
# get only finished english premier league matches
epl_matches <- matches[league_id == 148 & match_status == "Finished"]
# Construct histogram with home team scores.
h1 <- hist(epl_matches$match_hometeam_score, breaks = seq(-1, max(epl_matches$match_hometeam_score),1), xlab="Home Score(goals)", ylab="Number of Games", col = "red", main = "Home Score Histogram")
# x points for hometeam scores
xfit<-seq(min(epl_matches$match_hometeam_score)-1,max(epl_matches$match_hometeam_score),length=40)
# normalized values for y points
yfit<-dnorm(xfit,mean=mean(epl_matches$match_hometeam_score),sd=sd(epl_matches$match_hometeam_score))
yfit <- yfit*diff(h1$mids[1:2])*length(epl_matches$match_hometeam_score)
# draw normalized line
lines(xfit, yfit, col="blue", lwd=2)
```

```{r}
h2 <- hist(epl_matches$match_awayteam_score, breaks = seq(-1, max(epl_matches$match_awayteam_score),1), xlab="Away Score(goals)", ylab="Number of Games", col = "red", main = "Away Score Histogram")
xfit<-seq(min(epl_matches$match_awayteam_score)-1,max(epl_matches$match_awayteam_score),length=40)
yfit<-dnorm(xfit,mean=mean(epl_matches$match_awayteam_score),sd=sd(epl_matches$match_awayteam_score))
yfit <- yfit*diff(h2$mids[1:2])*length(epl_matches$match_awayteam_score)
lines(xfit, yfit, col="blue", lwd=2)
```

```{r}
epl_diff <- epl_matches$match_hometeam_score - epl_matches$match_awayteam_score
h3 <- hist(epl_diff, breaks = seq(min(epl_diff)-1, max(epl_diff),1), xlab="Home Goals - Away Goals", ylab="Number of Games", col = "red", main = "Home - Away Score Histogram")
xfit<-seq(min(epl_diff),max(epl_diff),length=40)
yfit<-dnorm(xfit,mean=mean(epl_diff),sd=sd(epl_diff))
yfit <- yfit*diff(h3$mids[1:2])*length(epl_diff)
lines(xfit, yfit, col="blue", lwd=2)
```

## Subtask 2
### Home team score (poisson)
```{r}
# show densities for each number of goals
h1_table = data.table(number_of_goals = h1$breaks[-1], probability = h1$density)
h1_table
mean_home_scores = mean(epl_matches$match_hometeam_score)
poisson_home = dpois(min(epl_matches$match_hometeam_score):max(epl_matches$match_hometeam_score), mean_home_scores)
poisson_home = round(poisson_home * nrow(epl_matches))
barplot(poisson_home, names.arg = h1$breaks[-1], xlab="Home Score(goals)", ylab="Number of Games", col = "red", main = "Home Score Poisson Histogram")
```
### Away team score (poisson)
```{r}
# show densities for each number of goals
h2_table = data.table(number_of_goals = h2$breaks[-1], probability = h2$density)
h2_table
mean_away_scores = mean(epl_matches$match_awayteam_score)
poisson_away = dpois(min(epl_matches$match_awayteam_score):max(epl_matches$match_awayteam_score), mean_away_scores)
poisson_away = round(poisson_away * nrow(epl_matches))
barplot(poisson_away, names.arg = h2$breaks[-1], xlab="Away Score(goals)", ylab="Number of Games", col = "red", main = "Away Score Poisson Histogram")
```
### Home - Away team score (poisson)
```{r}
# show densities for each number of goals
h3_table = data.table(number_of_goals = h3$breaks[-1], probability = h3$density)
h3_table
mean_ha_scores = mean(epl_diff)
poisson_ha = dnorm(min(epl_diff):max(epl_diff), mean=mean_ha_scores, sd = sd(epl_diff))
poisson_ha = round(poisson_ha * nrow(epl_matches))
barplot(poisson_ha, names.arg = h3$breaks[-1], xlab="Home - Away Score(goals)", ylab="Number of Games", col = "red", main = "Home - Away Score Poisson Histogram")
```
# Task 2
```{r}
# read bets csv
bets <- fread("/home/ceyonur/git/CMPE/fall19-ceyonur/data/homework1/bets.csv")
# add column to indicate if match ended as draw
epl_matches <- epl_matches[, is_draw := as.numeric(match_awayteam_score == match_hometeam_score)]
# get only bets data with win, draw or lose.
bets <- bets[variable %in% c("odd_1", "odd_x", "odd_2" )]
# join bets and match data by match_id
merged_data <- merge(epl_matches, bets, by='match_id')
# find the most active bookmaker
bookmaker_data_count <- bets[, .N, by = c("odd_bookmakers")]
bookmaker_data_count <- bookmaker_data_count[order(-N)]
# select the first 4 bookmaker name that has most bets
bookmaker_names <- bookmaker_data_count[1:4]$odd_bookmakers
bookmaker_data_count
bookmaker_names
```
### Custom functions:
```{r}
# Use this function to analyze for different bookmakers.
bookmaker_draw_analysis <- function(bookmaker_name, data) {
  # get the data with selected bookmaker
  bookmaker_bets <- data[odd_bookmakers == bookmaker_name]
  # find probabilities from given odds
  bookmaker_bets <- bookmaker_bets[, c("p_win", "p_draw", "p_lose") := list(1/value[variable == 'odd_1'], 1/value[variable == 'odd_x'], 1/value[variable == 'odd_2']), by = list(match_id, odd_bookmakers, variable)]
  # group data by match_id and odd_bookmakers, so that we can have only one row for each match and bookmaker
  bookmaker_bets <- aggregate(bookmaker_bets[,c("is_draw", "p_win","p_draw","p_lose")], by=list(bookmaker_bets$match_id, bookmaker_bets$odd_bookmakers), FUN = function (x) first(na.omit(x)))
  # convert it back to data table
  bookmaker_bets <- data.table(bookmaker_bets)
  # rename grouped columns
  names(bookmaker_bets)[1] <- "match_id"
  names(bookmaker_bets)[2] <- "odd_bookmakers"
  # TASK 2.2
  # convert probabilities by implied probability function for each probability type
  bookmaker_bets[, p_win_imp:=p_win / (p_win + p_draw + p_lose)]
  bookmaker_bets[, p_draw_imp:=p_draw / (p_win + p_draw + p_lose)]
  bookmaker_bets[, p_lose_imp:=p_lose / (p_win + p_draw + p_lose)]
  # add column for P(WIN - LOSE)
  bookmaker_bets[, p_win_lose_imp := p_win_imp - p_lose_imp]
}
```

```{r}
# Use this function to split data to bins
bookmaker_bin_table <- function(bookmaker_bets){
  # TASK 2.3
  # bookmaker odds may not be larger than certain values, so use the data to determine bins.
  cutpoints <- seq(min(bookmaker_bets$p_win_lose_imp) - 0.06, max(bookmaker_bets$p_win_lose_imp) + 0.06, 0.05)
  # split impled P(WIN-LOSE) to bins accordingly.
  bookmaker_bets[,w_l_cut:=cut(p_win_lose_imp, cutpoints)]
  # find mean for impled P(DRAW) in each bin and also find matches resulted with draw in each bin. Also take mean for drawe matches.
  bookmaker_bin_table <- bookmaker_bets[,list(emprical_over=mean(is_draw), probabilistic_over=mean(p_draw_imp),draw_count=sum(is_draw), total_count=.N),by=list(w_l_cut)]
  # Order by bins
  bookmaker_bin_table <- bookmaker_bin_table[order(w_l_cut)]
}
```
### First book maker
```{r}
# 1st
first_bookmaker_name <- bookmaker_names[1]
# Task 2.1-2
first_bets <- bookmaker_draw_analysis(first_bookmaker_name, merged_data)
first_bin_table <- bookmaker_bin_table(first_bets)
first_bets
first_bin_table
```
```{r}
# Task 2.3
# Plot the implied data
plot(first_bets$p_win_imp - first_bets$p_lose_imp, first_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = first_bookmaker_name)
```
```{r}
# Task 2.4
# Draw points for bins
plot(first_bin_table$w_l_cut, first_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = first_bookmaker_name)
# Draw both calculated emprical data(calculated result) and probabilistic(real draw) lines to compare. 
lines(lowess(first_bin_table$w_l_cut, first_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(first_bin_table$w_l_cut, first_bin_table$probabilistic_over), col="red", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability"), col=c("black","red"), lty=1:1, cex=0.8)
# 1xBet seems a good bookmaker since the real probability (given by bookmaker) is higher than the calculated one.
```
### Second Bookmaker
```{r}
# 2nd
second_bookmaker_name <- bookmaker_names[2]
# Task 2.1-2
second_bets <- bookmaker_draw_analysis(second_bookmaker_name, merged_data)
second_bin_table <- bookmaker_bin_table(second_bets)
second_bets
second_bin_table
```

```{r}
# Task 2.3
plot(second_bets$p_win_imp - second_bets$p_lose_imp, second_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = second_bookmaker_name)
```

```{r}
# Task 2.4
plot(second_bin_table$w_l_cut, second_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = second_bookmaker_name)
lines(lowess(second_bin_table$w_l_cut, second_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(second_bin_table$w_l_cut, second_bin_table$probabilistic_over), col="red", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability"), col=c("black","red"), lty=1:1, cex=0.8)
# bwin is arguably not a good bookmaker at the point(-0.491, -0.441) where probability lines crosses and calculated probability is higher than real one.
```
### Third bookmaker
```{r}
# 3rd
third_bookmaker_name <- bookmaker_names[3]
# Task 2.1-2
third_bets <- bookmaker_draw_analysis(third_bookmaker_name, merged_data)
third_bin_table <- bookmaker_bin_table(third_bets)
third_bets
third_bin_table
```
```{r}
# Task 2.3
plot(third_bets$p_win_imp - third_bets$p_lose_imp, third_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = third_bookmaker_name)
```
```{r}
# Task 2.4
plot(third_bin_table$w_l_cut, third_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = third_bookmaker_name)
lines(lowess(third_bin_table$w_l_cut, third_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(third_bin_table$w_l_cut, third_bin_table$probabilistic_over), col="red", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability"), col=c("black","red"), lty=1:1, cex=0.8)
# Unibet is also a good bookmaker.
```
```{r}
# 4th
fourth_bookmaker_name <- bookmaker_names[4]
# Task 2.1-2
fourth_bets <- bookmaker_draw_analysis(fourth_bookmaker_name, merged_data)
fourth_bin_table <- bookmaker_bin_table(fourth_bets)
fourth_bets
fourth_bin_table
```
```{r}
# Task 2.3
plot(fourth_bets$p_win_imp - fourth_bets$p_lose_imp, fourth_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = fourth_bookmaker_name)
```
```{r}
# Task 2.4
plot(fourth_bin_table$w_l_cut, fourth_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = fourth_bookmaker_name)
lines(lowess(fourth_bin_table$w_l_cut, fourth_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(fourth_bin_table$w_l_cut, fourth_bin_table$probabilistic_over), col="red", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability"), col=c("black","red"), lty=1:1, cex=0.8)
# Proposed(real) probability is higher, 18bet is also a good bookmaker. 
```
### Task 3
```{r}
# Read goal data
goals <- fread("/home/ceyonur/git/CMPE/fall19-ceyonur/data/homework1/goals.csv")
# Find goals scored after 90 (90 + x), 90 is not counted because 90 is considered to be in the match time.
goals <- goals[time > 90]
# Split goal data (x-x) to away and home score columns
goals <- goals[,c("home_score", "away_score") := tstrsplit(score, '-', type.convert = TRUE)]
# Find the score before the extra time score. So that we can find the score right before the extra times.
goals <- goals[, match_hometeam_endtime_score := home_score - (as.integer(home_scorer != ""))]
goals <- goals[, match_awayteam_endtime_score := away_score - (as.integer(away_scorer != ""))]
# Get rid of other extra time scores, since we aim to find the "before extra time" score.
goals <- goals[order(match_id, time)]
goals <- unique(goals, by="match_id")
goals
```
```{r}
# merge these data with english premier league data (left join).
merged <- merge(epl_matches, goals[, c("match_id", "match_hometeam_endtime_score", "match_awayteam_endtime_score")], all.x= TRUE)
# there could be some "NA" matches since there are some matches without any extra time needed. So we assume their "endtime" score as their final score.
merged <- merged[, match_hometeam_endtime_score := ifelse(is.na(match_hometeam_endtime_score),match_hometeam_score, match_hometeam_endtime_score)]
merged <- merged[, match_awayteam_endtime_score := ifelse(is.na(match_awayteam_endtime_score),match_awayteam_score, match_awayteam_endtime_score)]
# Calculate the final match result (home win = 1, away win = -1, draw = 0)
merged <- merged[, match_score_status := match_hometeam_score - match_awayteam_score]
merged <- merged[, match_score_status := ifelse(match_score_status == 0, 0, ifelse(match_score_status > 0, 1, -1))]
# Calculate also the "before extra time" match result.
merged <- merged[, match_endtime_score_status := match_hometeam_endtime_score - match_awayteam_endtime_score]
merged <- merged[, match_endtime_score_status := ifelse(match_endtime_score_status == 0, 0, ifelse(match_endtime_score_status > 0, 1, -1))]
# Find matches which has changed result after the extra times(endtime).
excluded_endtime_matches <- merged[match_endtime_score_status != match_score_status]
# count of excluded matches due to extra time score change.
nrow(excluded_endtime_matches)
```

```{r}
# read booking data
bookings <- fread("/home/ceyonur/git/CMPE/fall19-ceyonur/data/homework1/booking.csv")
# find matches with red card before 15 mins. 
excluded_bookings <- bookings[card == "red card" & time <= 15]
# count of excluded matches due to red card.
nrow(excluded_bookings)
```

```{r}
excluded_match_ids <- unique(c(excluded_endtime_matches$match_id, excluded_bookings$match_id))
'%!in%' <- function(x,y)!('%in%'(x,y))
excluded_merged_data = merged_data[match_id %!in% excluded_match_ids]
# removed match count
nrow(merged_data) - nrow(excluded_merged_data)
```
### Task 2 (after removing noise data)
### First bookmaker
```{r}
# 1st
first_excluded_bookmaker_name <- bookmaker_names[1]
# Task 2.1-2
first_excluded_bets <- bookmaker_draw_analysis(first_excluded_bookmaker_name, excluded_merged_data)
first_excluded_bin_table <- bookmaker_bin_table(first_excluded_bets)
# Task 2.3
plot(first_excluded_bets$p_win_imp - first_excluded_bets$p_lose_imp, first_excluded_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = first_excluded_bookmaker_name)
# Task 2.4
plot(first_excluded_bin_table$w_l_cut, first_excluded_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = first_excluded_bookmaker_name)
lines(lowess(first_excluded_bin_table$w_l_cut, first_excluded_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(first_excluded_bin_table$w_l_cut, first_excluded_bin_table$probabilistic_over), col="red", lwd=1)
lines(lowess(first_bin_table$w_l_cut, first_bin_table$emprical_over), col="green", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability", "Original Calculated Probability"), col=c("black","red", "green"), lty=1:1, cex=0.8)
# When we compare original (before excluding matches) with current calculated proability, there is no big differences. The current one is a little bit below than the original one.
```
### Second bookmaker
```{r}
# 2nd
second_excluded_bookmaker_name <- bookmaker_names[2]
# Task 2.1-2
second_excluded_bets <- bookmaker_draw_analysis(second_excluded_bookmaker_name, excluded_merged_data)
second_excluded_bin_table <- bookmaker_bin_table(second_excluded_bets)
# Task 2.3
plot(second_excluded_bets$p_win_imp - second_excluded_bets$p_lose_imp, second_excluded_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = second_excluded_bookmaker_name)
# Task 2.4
plot(second_excluded_bin_table$w_l_cut, second_excluded_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = second_excluded_bookmaker_name)
lines(lowess(second_excluded_bin_table$w_l_cut, second_excluded_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(second_excluded_bin_table$w_l_cut, second_excluded_bin_table$probabilistic_over), col="red", lwd=1)
lines(lowess(second_bin_table$w_l_cut, second_bin_table$emprical_over), col="green", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability", "Original Calculated Probability"), col=c("black","red", "green"), lty=1:1, cex=0.8)
# When we compare original (before excluding matches) with current calculated proability, there is no big differences. The current one is a little bit below than the original one.
```
### Third bookmaker
```{r}
# 3rd
third_excluded_bookmaker_name <- bookmaker_names[3]
# Task 2.1-2
third_excluded_bets <- bookmaker_draw_analysis(third_excluded_bookmaker_name, excluded_merged_data)
third_excluded_bin_table <- bookmaker_bin_table(third_excluded_bets)
# Task 2.3
plot(third_excluded_bets$p_win_imp - third_excluded_bets$p_lose_imp, third_excluded_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = third_excluded_bookmaker_name)
# Task 2.4
plot(third_excluded_bin_table$w_l_cut, third_excluded_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = third_excluded_bookmaker_name)
lines(lowess(third_excluded_bin_table$w_l_cut, third_excluded_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(third_excluded_bin_table$w_l_cut, third_excluded_bin_table$probabilistic_over), col="red", lwd=1)
lines(lowess(third_bin_table$w_l_cut, third_bin_table$emprical_over), col="green", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability", "Original Calculated Probability"), col=c("black","red", "green"), lty=1:1, cex=0.8)
# This one has a much bigger difference between original and current probability line. Seems like bookmaker considered the situtations more accuratly than other bookmakers. Since the calculated probability is further away from the proposed probability.
```
### Fourth bookmaker
```{r}
# 4th
fourth_excluded_bookmaker_name <- bookmaker_names[4]
# Task 2.1-2
fourth_excluded_bets <- bookmaker_draw_analysis(fourth_excluded_bookmaker_name, excluded_merged_data)
fourth_excluded_bin_table <- bookmaker_bin_table(fourth_excluded_bets)
# Task 2.3
plot(fourth_excluded_bets$p_win_imp - fourth_excluded_bets$p_lose_imp, fourth_excluded_bets$p_draw_imp,cex=0.5,col='red',xlab="P(WIN_IMP) - P(LOSE_IMP)", ylab="P(DRAW_IMP)", main = fourth_excluded_bookmaker_name)
# Task 2.4
plot(fourth_excluded_bin_table$w_l_cut, fourth_excluded_bin_table$emprical_over,ylab="P(DRAW)",xlab="bin", main = fourth_excluded_bookmaker_name)
lines(lowess(fourth_excluded_bin_table$w_l_cut, fourth_excluded_bin_table$emprical_over), col="black", lwd=1)
lines(lowess(fourth_excluded_bin_table$w_l_cut, fourth_excluded_bin_table$probabilistic_over), col="red", lwd=1)
lines(lowess(fourth_bin_table$w_l_cut, fourth_bin_table$emprical_over), col="green", lwd=1)
legend("topright", legend=c("Calculated Probability", "Real Probability", "Original Calculated Probability"), col=c("black","red", "green"), lty=1:1, cex=0.8)
# When we compare original (before excluding matches) with current calculated proability, there is no big differences. The current one is a little bit below than the original one.
```